"""Creacion BD

Revision ID: 4a5f6de76b66
Revises: 
Create Date: 2025-10-02 21:13:34.250541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5f6de76b66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=60), nullable=True),
    sa.Column('ubicacion', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=800), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imagen', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=60), nullable=True),
    sa.Column('contactoUsuario', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('destinos')
    # ### end Alembic commands ###
